<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeBonusManagement.Application\EmployeeBonusManagement.Application.csproj" />
    <ProjectReference Include="..\EmployeeBonusManagement.Core\EmployeeBonusManagement.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dapper\" />
  </ItemGroup>

</Project>
